local deftest = require("deftest.deftest")

function init(self)
	deftest.add(require("test.test_event"))
	deftest.add(require("test.test_event_logger"))
	deftest.add(require("test.test_events"))
	deftest.add(require("test.test_event_context_manager"))
	deftest.add(require("test.test_event_context_change"))

	-- Ensure all other script init has been processed before
	-- Required for context changing tests
	timer.delay(0, false, function()
		local is_report = sys.get_config("test.report") == "1"
		deftest.run({ coverage = { enabled = is_report } })
	end)
end
